const translations = {
    en: {
        brand: "Raju Ahmed",
        nav_intro: "Intro",
        nav_skills: "Skills",
        nav_projects: "Projects",
        nav_certificates: "Certificates",
        nav_contact: "Contact",
        nav_language: "English",
        banner_title: "Hi, I'm Raju Ahmed",
        banner_description: "A passionate Software Engineering Intern with a focus on creating scalable software solutions. I specialize in building robust Frontend and backend systems and web applications. Currently pursuing my Bachelor's in Information Technology at Taylor’s University, Selangor, Malaysia.",
        banner_button: "Let's Connect",
        about_title: "About Me",
        about_paragraph_1: "I’m a Software Engineer Intern with a strong background in web development. I specialize in creating efficient, user-centric applications and backend systems. Currently, I am gaining hands-on experience in optimizing performance and delivering scalable solutions.",
        about_paragraph_2: "With my academic journey and practical skills, I’m eager to contribute to impactful projects, continuously improving and growing as a developer.",
        skills_title: "Skills",
        frontend_title: "Frontend Development",
        frontend_description: "HTML, CSS, JavaScript, React.js, Vue.js",
        backend_title: "Backend Development",
        backend_description: "PHP, Python, Node.js, MySQL",
        tools_title: "Tools & Frameworks",
        tools_description: "Git, Bootstrap, Debugging Tools",
        additional_tools_title: "Additional Tools",
        additional_tools_description: "Canva, Figma, JustInMind, Adobe Illustrator",
        expertise_title: "Expertise",
        web_dev_title: "Web Development",
        web_dev_description: "Building responsive, dynamic websites with modern technologies.",
        it_support_title: "IT Support",
        it_support_description: "Providing technical support for troubleshooting and issue resolution.",
        ecommerce_title: "E-Commerce",
        ecommerce_description: "Developing scalable, user-friendly e-commerce platforms.",
        project_management_title: "Project Management",
        project_management_description: "Managing and coordinating projects from inception to completion.",
        team_collaboration_title: "Team Collaboration",
        team_collaboration_description: "Facilitating efficient teamwork and communication.",
        leadership_title: "Leadership",
        leadership_description: "Leading and motivating teams to achieve their best performance.",
        projects_title: "Projects",
        cyber_patrol_title: "Cyber Patrol",
        cyber_patrol_description: "A gamified cybersecurity app for teenagers using Laravel and Flutter.",
        nasi_kandar_title: "Nasi Kandar WAP",
        nasi_kandar_description: "A restaurant management system optimized for performance.",
        hxred_wallet_title: "Hxred Wallet",
        hxred_wallet_description: "An educational e-wallet system with real-time budget tracking.",
        ngo_project_title: "Ngo Project",
        ngo_project_description: "A platform designed to streamline non-profit organization management and operations.",
        library_management_title: "Library Management System",
        library_management_description: "A system to manage library books, users, and borrowing processes efficiently.",
        sdg_project_title: "SDG Project App",
        sdg_project_description: "An app dedicated to promoting and selling reusable products aligned with SDGs.",
        work_experience_title: "Work Experience",
        ict_tutor_title: "Online ICT Tutor (Part-Time)",
        ict_tutor_year: "2021",
        ict_tutor_description: "Taught basic ICT concepts, including computer fundamentals and MS Office tools.",
        it_help_title: "IT Help Desk (Part-Time)",
        it_help_year: "2020",
        it_help_description: "Provided remote IT support for productivity tools like Excel, Word, and PowerPoint.",
        graphics_designer_title: "Graphics Designer (Part-Time)",
        graphics_designer_year: "2019 - 2021",
        graphics_designer_description: "Designed visuals for branding, marketing, and social media campaigns.",
        ecommerce_admin_title: "E-Commerce Page Admin (Part-Time)",
        ecommerce_admin_year: "2022 - 2023",
        ecommerce_admin_description: "Managed the Pushpokola Facebook page and Marketplace presence for showpieces.",
        certificates_title: "Certificates",
        aws_ec2_certificate: "Build with Amazon EC2",
        data_analysis_certificate: "Data Analysis with Python",
        blockchain_aws_certificate: "Designing Blockchain Solutions with AWS",
        aws_ecs_certificate: "Getting Started with Amazon ECS",
        mysql_certificate: "Getting Started with MySQL Command Line",
        responsible_ai_certificate: "Introduction to Responsible AI",
        contact_title: "Contact Me",
        contact_name_label: "Your Name",
        contact_name_placeholder: "Enter Your Name",
        contact_email_label: "Email Address",
        contact_email_placeholder: "Enter Your Email",
        contact_message_label: "Message",
        contact_message_placeholder: "Enter Your Message",
        contact_submit_button: "Send Message",
        footer_contact_title: "Contact",
        footer_location_title: "Location",
        footer_location_taylors: "Taylor’s University, Subang Jaya",
        footer_location_kl: "Kuala Lumpur, Malaysia",
        footer_quick_links_title: "Quick Links",
        footer_link_about: "About Me",
        footer_link_skills: "Skills",
        footer_link_projects: "Projects",
        footer_link_certificates: "Certificates",
        footer_link_work_experince:"Work Experince",
        footer_link_contact: "Contact",
        footer_subscribe_title: "Subscribe",
        footer_subscribe_description: "Get the latest updates and insights directly to your inbox.",
        footer_subscribe_name_placeholder: "Your Name",
        footer_subscribe_email_placeholder: "Your Email",
        footer_subscribe_button: "Subscribe"
    },
    mal: {
        brand: "Raju Ahmed",
        nav_intro: "Pengenalan",
        nav_skills: "Kemahiran",
        nav_projects: "Projek",
        nav_certificates: "Sijil",
        nav_contact: "Hubungi",
        nav_language: "Bahasa Melayu",
        banner_title: "Hai, Saya Raju Ahmed",
        banner_description: "Seorang Pelatih Kejuruteraan Perisian yang bersemangat dengan tumpuan untuk mencipta penyelesaian perisian berskala. Saya pakar dalam membina sistem Frontend dan backend yang mantap dan aplikasi web. Sedang melanjutkan pengajian saya dalam Ijazah Sarjana Muda Teknologi Maklumat di Taylor’s University, Selangor, Malaysia..",
        banner_button: "Mari Berhubung",
        about_title: "Tentang Saya",
        about_paragraph_1: "Saya seorang Jurutera Perisian Intern dengan latar belakang yang kukuh dalam pembangunan web. Saya pakar dalam mencipta aplikasi dan sistem hujung belakang yang cekap, mengutamakan pengguna. Pada masa ini, saya memperoleh pengalaman praktikal dalam mengoptimumkan prestasi dan menyampaikan penyelesaian berskala.",
        about_paragraph_2: "Dengan perjalanan akademik dan kemahiran praktikal saya, saya tidak sabar-sabar untuk menyumbang kepada projek yang memberi impak, terus bertambah baik dan berkembang sebagai pemaju..",
        skills_title: "Kemahiran",
        frontend_title: "Pembangunan Frontend",
        frontend_description: "HTML, CSS, JavaScript, React.js, Vue.js",
        backend_title: "Pembangunan Backend",
        backend_description: "PHP, Python, Node.js, MySQL",
        tools_title: "Alat & Rangka Kerja",
        tools_description: "Git, Bootstrap, Alat Debugging",
        additional_tools_title: "Alat Tambahan",
        additional_tools_description: "Canva, Figma, JustInMind, Adobe Illustrator",
        expertise_title: "Kepakaran",
        web_dev_title: "Pembangunan Web",
        web_dev_description: "Membangunkan laman web responsif dan dinamik dengan teknologi moden.",
        it_support_title: "Sokongan IT",
        it_support_description: "Memberi sokongan teknikal untuk penyelesaian masalah dan isu teknikal.",
        ecommerce_title: "E-Dagang",
        ecommerce_description: "Membangunkan platform e-dagang yang boleh diskalakan dan mesra pengguna.",
        project_management_title: "Pengurusan Projek",
        project_management_description: "Mengurus dan menyelaras projek dari permulaan hingga selesai.",
        team_collaboration_title: "Kerjasama Pasukan",
        team_collaboration_description: "Memudahkan kerja berpasukan dan komunikasi yang cekap.",
        leadership_title: "Kepimpinan",
        leadership_description: "Memimpin dan memberi motivasi kepada pasukan untuk mencapai prestasi terbaik.",
        projects_title: "Projek",
        cyber_patrol_title: "Cyber Patrol",
        cyber_patrol_description: "Aplikasi keselamatan siber berunsur permainan untuk remaja menggunakan Laravel dan Flutter.",
        nasi_kandar_title: "Nasi Kandar WAP",
        nasi_kandar_description: "Sistem pengurusan restoran yang dioptimumkan untuk prestasi.",
        hxred_wallet_title: "Dompet Hxred",
        hxred_wallet_description: "Sistem e-dompet pendidikan dengan pengesanan belanjawan masa nyata.",
        ngo_project_title: "Projek NGO",
        ngo_project_description: "Platform untuk menyelaraskan pengurusan dan operasi organisasi bukan untung.",
        library_management_title: "Sistem Pengurusan Perpustakaan",
        library_management_description: "Sistem untuk menguruskan buku perpustakaan, pengguna, dan proses pinjaman dengan cekap.",
        sdg_project_title: "Aplikasi Projek SDG",
        sdg_project_description: "Aplikasi untuk mempromosikan dan menjual produk guna semula selaras dengan SDG.",
        work_experience_title: "Pengalaman Kerja",
        ict_tutor_title: "Tutor ICT Dalam Talian (Separuh Masa)",
        ict_tutor_year: "2021",
        ict_tutor_description: "Mengajar asas ICT, termasuk asas komputer dan alat MS Office.",
        it_help_title: "Meja Bantuan IT (Separuh Masa)",
        it_help_year: "2020",
        it_help_description: "Memberikan sokongan IT jarak jauh untuk alat produktiviti seperti Excel dan Word.",
        graphics_designer_title: "Pereka Grafik (Separuh Masa)",
        graphics_designer_year: "2019 - 2021",
        graphics_designer_description: "Mereka bentuk visual untuk penjenamaan dan kempen media sosial.",
        ecommerce_admin_title: "Pentadbir Halaman E-Dagang (Separuh Masa)",
        ecommerce_admin_year: "2022 - 2023",
        ecommerce_admin_description: "Mengurus halaman Facebook Pushpokola dan kandungan Marketplace.",
        certificates_title: "Sijil",
        aws_ec2_certificate: "Bina dengan Amazon EC2",
        data_analysis_certificate: "Analisis Data dengan Python",
        blockchain_aws_certificate: "Reka Bentuk Penyelesaian Blockchain dengan AWS",
        aws_ecs_certificate: "Bermula dengan Amazon ECS",
        mysql_certificate: "Bermula dengan MySQL Command Line",
        responsible_ai_certificate: "Pengenalan kepada AI Bertanggungjawab",
        contact_title: "Hubungi Saya",
        contact_name_label: "Nama Anda",
        contact_name_placeholder: "Masukkan Nama Anda",
        contact_email_label: "Alamat Emel",
        contact_email_placeholder: "Masukkan Emel Anda",
        contact_message_label: "Mesej",
        contact_message_placeholder: "Masukkan Mesej Anda",
        contact_submit_button: "Hantar Mesej",
        footer_contact_title: "Hubungi",
        footer_location_title: "Lokasi",
        footer_location_taylors: "Taylor’s University, Subang Jaya",
        footer_location_kl: "Kuala Lumpur, Malaysia",
        footer_quick_links_title: "Pautan Pantas",
        footer_link_about: "Tentang Saya",
        footer_link_skills: "Kemahiran",
        footer_link_projects: "Projek",
        footer_link_certificates: "Sijil",
        footer_link_work_experince:"Pengalaman Kerja",
        footer_link_contact: "Hubungi",
        footer_subscribe_title: "Langgan",
        footer_subscribe_description: "Dapatkan kemas kini dan pandangan terkini terus ke peti masuk anda.",
        footer_subscribe_name_placeholder: "Nama Anda",
        footer_subscribe_email_placeholder: "Emel Anda",
        footer_subscribe_button: "Langgan"
    },
    sp: {
        brand: "Raju Ahmed",
        nav_intro: "Introducción",
        nav_skills: "Habilidades",
        nav_projects: "Proyectos",
        nav_certificates: "Certificados",
        nav_contact: "Contacto",
        nav_language: "Español",
        banner_title: "Hola, soy Raju Ahmed",
        banner_description: "Un apasionado pasante de ingeniería de software enfocado en la creación de soluciones de software escalables. Me especializo en la construcción de sistemas frontend y backend robustos y aplicaciones web. Actualmente estoy cursando mi Licenciatura en Tecnología de la Información en la Universidad de Taylor, Selangor, Malasia.",
        banner_button: "Conectemos",
        about_title: "Sobre mí",
        about_paragraph_1: "Soy un ingeniero de software en prácticas con una sólida experiencia en desarrollo web. Me especializo en la creación de aplicaciones y sistemas backend eficientes y centrados en el usuario. Actualmente, estoy adquiriendo experiencia práctica en la optimización del rendimiento y la entrega de soluciones escalables.",
        about_paragraph_2: "Con mi trayectoria académica y habilidades prácticas, estoy ansioso por contribuir a proyectos impactantes, mejorando y creciendo continuamente como desarrollador.",
        skills_title: "Habilidades",
        frontend_title: "Desarrollo Frontend",
        frontend_description: "HTML, CSS, JavaScript, React.js, Vue.js",
        backend_title: "Desarrollo Backend",
        backend_description: "PHP, Python, Node.js, MySQL",
        tools_title: "Herramientas y Frameworks",
        tools_description: "Git, Bootstrap, Herramientas de Depuración",
        additional_tools_title: "Herramientas Adicionales",
        additional_tools_description: "Canva, Figma, JustInMind, Adobe Illustrator",
        expertise_title: "Pericia",
        web_dev_title: "Desarrollo Web",
        web_dev_description: "Construcción de sitios web dinámicos y responsivos con tecnologías modernas.",
        it_support_title: "Soporte de IT",
        it_support_description: "Proporcionar soporte técnico para resolución de problemas.",
        ecommerce_title: "Comercio Electrónico",
        ecommerce_description: "Desarrollo de plataformas de comercio electrónico escalables y fáciles de usar.",
        project_management_title: "Gestión de Proyectos",
        project_management_description: "Gestión y coordinación de proyectos desde el inicio hasta la finalización.",
        team_collaboration_title: "Colaboración en Equipo",
        team_collaboration_description: "Facilitando el trabajo en equipo y la comunicación eficiente.",
        leadership_title: "Liderazgo",
        leadership_description: "Liderar y motivar equipos para lograr el mejor rendimiento.",
        projects_title: "Proyectos",
        cyber_patrol_title: "Patrulla Cibernética",
        cyber_patrol_description: "Una aplicación gamificada de ciberseguridad para adolescentes.",
        nasi_kandar_title: "Nasi Kandar WAP",
        nasi_kandar_description: "Un sistema de gestión de restaurantes optimizado para el rendimiento.",
        hxred_wallet_title: "Cartera Hxred",
        hxred_wallet_description: "Un sistema educativo de cartera electrónica con seguimiento presupuestario en tiempo real.",
        ngo_project_title: "Proyecto ONG",
        ngo_project_description: "Plataforma diseñada para optimizar la gestión de organizaciones sin fines de lucro.",
        library_management_title: "Sistema de Gestión de Bibliotecas",
        library_management_description: "Sistema para gestionar libros, usuarios y procesos de préstamo.",
        sdg_project_title: "Aplicación de Proyecto ODS",
        sdg_project_description: "Aplicación para promover y vender productos reutilizables.",
        work_experience_title: "Experiencia Laboral",
        ict_tutor_title: "Tutor de TIC en Línea (Medio Tiempo)",
        ict_tutor_year: "2021",
        ict_tutor_description: "Enseñanza de conceptos básicos de TIC, incluyendo fundamentos de computación.",
        it_help_title: "Mesa de Ayuda de IT (Medio Tiempo)",
        it_help_year: "2020",
        it_help_description: "Soporte remoto de IT para herramientas como Excel y Word.",
        graphics_designer_title: "Diseñador Gráfico (Medio Tiempo)",
        graphics_designer_year: "2019 - 2021",
        graphics_designer_description: "Diseño de visuales para branding y campañas de redes sociales.",
        ecommerce_admin_title: "Administrador de Página de Comercio Electrónico",
        ecommerce_admin_year: "2022 - 2023",
        ecommerce_admin_description: "Gestión de la página de Pushpokola en Facebook y Marketplace.",
        certificates_title: "Certificados",
        aws_ec2_certificate: "Construir con Amazon EC2",
        data_analysis_certificate: "Análisis de Datos con Python",
        blockchain_aws_certificate: "Diseño de Soluciones Blockchain con AWS",
        aws_ecs_certificate: "Introducción a Amazon ECS",
        mysql_certificate: "Introducción a la Línea de Comandos de MySQL",
        responsible_ai_certificate: "Introducción a la IA Responsable",
        contact_title: "Contáctame",
        contact_name_label: "Tu Nombre",
        contact_name_placeholder: "Introduce tu nombre",
        contact_email_label: "Correo Electrónico",
        contact_email_placeholder: "Introduce tu correo electrónico",
        contact_message_label: "Mensaje",
        contact_message_placeholder: "Introduce tu mensaje",
        contact_submit_button: "Enviar Mensaje",
        footer_contact_title: "Contacto",
        footer_location_title: "Ubicación",
        footer_location_taylors: "Taylor’s University, Subang Jaya",
        footer_location_kl: "Kuala Lumpur, Malasia",
        footer_quick_links_title: "Enlaces Rápidos",
        footer_link_about: "Sobre mí",
        footer_link_skills: "Habilidades",
        footer_link_projects: "Proyectos",
        footer_link_certificates: "Certificados",
        footer_link_work_experince:"Experiencia Laboral",
        footer_link_contact: "Contacto",
        footer_subscribe_title: "Suscribirse",
        footer_subscribe_description: "Recibe las últimas actualizaciones directamente en tu correo.",
        footer_subscribe_name_placeholder: "Tu Nombre",
        footer_subscribe_email_placeholder: "Tu Correo",
        footer_subscribe_button: "Suscribirse"
    }
};
function switchLanguage(language) {
    const elementsToTranslate = document.querySelectorAll("[data-translate]");
    elementsToTranslate.forEach((element) => {
        const translationKey = element.getAttribute("data-translate");
        if (translations[language] && translations[language][translationKey]) {
            element.textContent = translations[language][translationKey];
        }
    });

    // Update the displayed language in the dropdown
    const languageLabel = translations[language]["nav_language"];
    document.querySelector("#languageDropdown span").textContent = languageLabel;
}